server:
  port: 8080

spring:
  application:
    name: postcode-services
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:postcode-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:db/testdata.sql






